###
### INTERNET
###

- id: internet_slow
  alias: internet_slow
  initial_state: on
  trigger:
    platform: state
    entity_id: binary_sensor.internet_slow
  condition:
    - condition: template
      value_template: >
        {{ states.binary_sensor.internet_slow.state == 'on' }}
  action:
    - service: persistent_notification.create
      data_template:
        title: >
          Internet slow at
          {{ states.sensor.internet_test.attributes.date | int | timestamp_custom("%a %b %d %I:%M %p") }}
        notification_id: internet_slow
        message: >
          Current: {{ states.sensor.internet_test_receive.state }} Mbps; 
          average {{ states.sensor.internet_receive_mean.state }} Mbps;
          stdev {{ states.sensor.internet_receive_statistics_mean.attributes.standard_deviation }} Mbps
    - service: mqtt.publish
      data_template:
        topic: 'status/internet/download'
        retain: false
        payload: >
          {{ states.sensor.internet_receive_statistics_mean.attributes }}

- id: internet_slow_dismiss
  alias: internet_slow_dismiss
  initial_state: on
  trigger:
    platform: state
    entity_id: binary_sensor.internet_slow
  condition:
    - condition: template
      value_template: >
        {{ states.binary_sensor.internet_slow.state == 'off' }}
  action:
    - service: persistent_notification.dismiss
      data_template:
        notification_id: internet_slow

- id: internet_fast
  alias: internet_fast
  initial_state: on
  trigger:
    platform: state
    entity_id: binary_sensor.internet_fast
  condition:
    - condition: template
      value_template: >
        {{ states.binary_sensor.internet_fast.state == 'on' }}
  action:
    - service: persistent_notification.create
      data_template:
        title: >
          Internet fast at
          {{ states.sensor.internet_test.attributes.date | int | timestamp_custom("%a %b %d %I:%M %p") }}
        notification_id: internet_fast
        message: >
          Current: {{ states.sensor.internet_test_receive.state }} Mbps; 
          average {{ states.sensor.internet_receive_mean.state }} Mbps;
          stdev {{ states.sensor.internet_receive_statistics_mean.attributes.standard_deviation }} Mbps
    - service: mqtt.publish
      data_template:
        topic: 'status/internet/download'
        retain: false
        payload: >
          {{ states.sensor.internet_receive_statistics_mean.attributes }}

- id: internet_fast_dismiss
  alias: internet_fast_dismiss
  initial_state: on
  trigger:
    platform: state
    entity_id: binary_sensor.internet_fast
  condition:
    - condition: template
      value_template: >
        {{ states.binary_sensor.internet_fast.state == 'off' }}
  action:
    - service: persistent_notification.dismiss
      data_template:
        notification_id: internet_fast

- id: internet_slow_persistent
  alias: internet_slow_persistent
  initial_state: on
  trigger:
    platform: state
    entity_id: binary_sensor.internet_slow_persistent
  condition:
    - condition: template
      value_template: >
        {{ states.binary_sensor.internet_slow_persistent.state == 'on' }}
  action:
    - service: persistent_notification.create
      data_template:
        title: >
          Internet slowing at
          {{ states.sensor.internet_test.attributes.date | int | timestamp_custom("%a %b %d %I:%M %p") }}
        notification_id: internet_slow
        message: >
          Current: {{ states.sensor.internet_test_receive.state }} Mbps; 
          average {{ states.sensor.internet_receive_mean.state }} Mbps;
          average stdev {{ states.sensor.internet_receive_stdev_mean.state }} Mbps
    - service: mqtt.publish
      data_template:
        topic: 'status/internet/download/stdev'
        retain: false
        payload: >
          {{ states.sensor.internet_receive_stdev_mean.attributes }}

- id: internet_fast_persistent
  alias: internet_fast_persistent
  initial_state: on
  trigger:
    platform: state
    entity_id: binary_sensor.internet_fast_persistent
  condition:
    - condition: template
      value_template: >
        {{ states.binary_sensor.internet_fast_persistent.state == 'on' }}
  action:
    - service: persistent_notification.create
      data_template:
        title: >
          Internet improving at
          {{ states.sensor.internet_test.attributes.date | int | timestamp_custom("%a %b %d %I:%M %p") }}
        notification_id: internet_fast
        message: >
          Current: {{ states.sensor.internet_test_receive.state }} Mbps; 
          average {{ states.sensor.internet_receive_mean.state }} Mbps;
          average stdev {{ states.sensor.internet_receive_stdev_mean.state }} Mbps
    - service: mqtt.publish
      data_template:
        topic: 'status/internet/download/stdev'
        retain: false
        payload: >
          {{ states.sensor.internet_receive_stdev_mean.attributes }}

###
### INTRANET
###

- id: intranet_slow
  alias: intranet_slow
  initial_state: on
  trigger:
    platform: state
    entity_id: binary_sensor.intranet_slow
  condition:
    - condition: template
      value_template: >
        {{ states.binary_sensor.intranet_slow.state == 'on' }}
  action:
    - service: persistent_notification.create
      data_template:
        title: >
          Internet slow at
          {{ states.sensor.intranet_test.attributes.date | int | timestamp_custom("%a %b %d %I:%M %p") }}
        notification_id: intranet_slow
        message: >
          Current: {{ states.sensor.intranet_test_receive.state }} Mbps; 
          average {{ states.sensor.intranet_receive_mean.state }} Mbps;
          stdev {{ states.sensor.intranet_receive_statistics_mean.attributes.standard_deviation }} Mbps
    - service: mqtt.publish
      data_template:
        topic: 'status/intranet/download'
        retain: false
        payload: >
          {{ states.sensor.intranet_receive_statistics_mean.attributes }}

- id: intranet_slow_dismiss
  alias: intranet_slow_dismiss
  initial_state: on
  trigger:
    platform: state
    entity_id: binary_sensor.intranet_slow
  condition:
    - condition: template
      value_template: >
        {{ states.binary_sensor.intranet_slow.state == 'off' }}
  action:
    - service: persistent_notification.dismiss
      data_template:
        notification_id: intranet_slow

- id: intranet_fast
  alias: intranet_fast
  initial_state: on
  trigger:
    platform: state
    entity_id: binary_sensor.intranet_fast
  condition:
    - condition: template
      value_template: >
        {{ states.binary_sensor.intranet_fast.state == 'on' }}
  action:
    - service: persistent_notification.create
      data_template:
        title: >
          Internet fast at
          {{ states.sensor.intranet_test.attributes.date | int | timestamp_custom("%a %b %d %I:%M %p") }}
        notification_id: intranet_fast
        message: >
          Current: {{ states.sensor.intranet_test_receive.state }} Mbps; 
          average {{ states.sensor.intranet_receive_mean.state }} Mbps;
          stdev {{ states.sensor.intranet_receive_statistics_mean.attributes.standard_deviation }} Mbps
    - service: mqtt.publish
      data_template:
        topic: 'status/intranet/download'
        retain: false
        payload: >
          {{ states.sensor.intranet_receive_statistics_mean.attributes }}

- id: intranet_fast_dismiss
  alias: intranet_fast_dismiss
  initial_state: on
  trigger:
    platform: state
    entity_id: binary_sensor.intranet_fast
  condition:
    - condition: template
      value_template: >
        {{ states.binary_sensor.intranet_fast.state == 'off' }}
  action:
    - service: persistent_notification.dismiss
      data_template:
        notification_id: intranet_fast

- id: intranet_slow_persistent
  alias: intranet_slow_persistent
  initial_state: on
  trigger:
    platform: state
    entity_id: binary_sensor.intranet_slow_persistent
  condition:
    - condition: template
      value_template: >
        {{ states.binary_sensor.intranet_slow_persistent.state == 'on' }}
  action:
    - service: persistent_notification.create
      data_template:
        title: >
          Internet slowing at
          {{ states.sensor.intranet_test.attributes.date | int | timestamp_custom("%a %b %d %I:%M %p") }}
        notification_id: intranet_slow
        message: >
          Current: {{ states.sensor.intranet_test_receive.state }} Mbps; 
          average {{ states.sensor.intranet_receive_mean.state }} Mbps;
          average stdev {{ states.sensor.intranet_receive_stdev_mean.state }} Mbps
    - service: mqtt.publish
      data_template:
        topic: 'status/intranet/download/stdev'
        retain: false
        payload: >
          {{ states.sensor.intranet_receive_stdev_mean.attributes }}

- id: intranet_fast_persistent
  alias: intranet_fast_persistent
  initial_state: on
  trigger:
    platform: state
    entity_id: binary_sensor.intranet_fast_persistent
  condition:
    - condition: template
      value_template: >
        {{ states.binary_sensor.intranet_fast_persistent.state == 'on' }}
  action:
    - service: persistent_notification.create
      data_template:
        title: >
          Internet improving at
          {{ states.sensor.intranet_test.attributes.date | int | timestamp_custom("%a %b %d %I:%M %p") }}
        notification_id: intranet_fast
        message: >
          Current: {{ states.sensor.intranet_test_receive.state }} Mbps; 
          average {{ states.sensor.intranet_receive_mean.state }} Mbps;
          average stdev {{ states.sensor.intranet_receive_stdev_mean.state }} Mbps
    - service: mqtt.publish
      data_template:
        topic: 'status/intranet/download/stdev'
        retain: false
        payload: >
          {{ states.sensor.intranet_receive_stdev_mean.attributes }}

###
### MOTION
###
- id: motion_event_end_notify
  alias: 'motion_event_end_notify'
  initial_state: 'on'
  trigger:
    - platform: mqtt
      topic: 'motion/+/+/event/end'
  condition:
    condition: template
    value_template: >
      {{ is_state('input_boolean.motion_event_notify','on') }}
  action:
    - service: persistent_notification.create
      data_template:
        title: >
          Motion {{ trigger.payload_json.camera }} camera
        notification_id: >
          {{ trigger.payload_json.device }}
        message: >-
          Detected {{ trigger.payload_json.elapsed }} seconds ({{trigger.payload_json.images|length}} frames) on
          {{ trigger.payload_json.date|int|timestamp_custom("%a %b %d @ %I:%M %p") | default(null) }}
- id: motion_camera_status_notify
  alias: 'motion_camera_status_notify'
  initial_state: 'on'
  trigger:
    - platform: mqtt
      topic: 'motion/+/+/status/+'
  condition:
    condition: template
    value_template: >
      {{ is_state('input_boolean.motion_status_notify','on') }}
  action:
    - service: persistent_notification.create
      data_template:
        title: >
          Camera {{ trigger.payload_json.camera }} {{ trigger.payload_json.status }}
        notification_id: >
          {{ trigger.payload_json.device }}
        message: >-
          Camera {{ trigger.payload_json.camera }} on device {{ trigger.payload_json.device }} {{ trigger.payload_json.status }} at
          {{ trigger.payload_json.time|int|timestamp_custom("%a %b %d @ %I:%M %p") | default(null) }}
- id: motion_camera_network_status_notify
  alias: 'motion_camera_network_status_notify'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id:
        - group.motion_camera_network_status
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: >
          {{ is_state('input_boolean.motion_status_notify','on') }}
      - condition: template
        value_template: >
          {{ (trigger.from_state != None) and ((trigger.from_state.state|lower) != "unknown") and (trigger.to_state.state != trigger.from_state.state) }}
  action:
    - service: persistent_notification.create
      data_template:
        title: >
          {{ state_attr(trigger.entity_id,"friendly_name") }} Status
        notification_id: >
          {{ state_attr(trigger.entity_id,"friendly_name") }}
          # {{ trigger.entity_id }}
        message: >
          {{ trigger.to_state.attributes.friendly_name }} changed from {{ trigger.from_state.state }} to {{ trigger.to_state.state }}

###
### YOLO
###

- id: yolo2msghub_activity_low
  alias: yolo2msghub_activity_low
  initial_state: on
  trigger:
    platform: state
    entity_id: binary_sensor.yolo2msghub_activity_low
  condition:
    - condition: template
      value_template: >
        {{ states.binary_sensor.yolo2msghub_activity_low.state == 'on' }}
  action:
    - service: persistent_notification.create
      data_template:
        title: >
          Activity low at
          {{ states.sensor.yolo2msghub_event.attributes.yolo2msghub.date | int | timestamp_custom("%a %b %d %I:%M %p") }}
        notification_id: yolo2msghub_activity_low
        message: >
          Current: {{ states.sensor.yolo2msghub_event_activity_count.state }} clients; 
          average {{ states.sensor.yolo2msghub_event_activity_count_mean.state }} clients;
          stdev {{ states.sensor.yolo2msghub_event_activity_count_statistics_mean.attributes.standard_deviation }} clients
    - service: mqtt.publish
      data_template:
        topic: 'status/yolo2msghub_activity/download'
        retain: false
        payload: >
          {{ states.sensor.yolo2msghub_event_activity_count_statistics_mean.attributes }}

- id: yolo2msghub_activity_low_dismiss
  alias: yolo2msghub_activity_low_dismiss
  initial_state: on
  trigger:
    platform: state
    entity_id: binary_sensor.yolo2msghub_activity_low
  condition:
    - condition: template
      value_template: >
        {{ states.binary_sensor.yolo2msghub_activity_low.state == 'off' }}
  action:
    - service: persistent_notification.dismiss
      data_template:
        notification_id: yolo2msghub_activity_low

- id: yolo2msghub_activity_high
  alias: yolo2msghub_activity_high
  initial_state: on
  trigger:
    platform: state
    entity_id: binary_sensor.yolo2msghub_activity_high
  condition:
    - condition: template
      value_template: >
        {{ states.binary_sensor.yolo2msghub_activity_high.state == 'on' }}
  action:
    - service: persistent_notification.create
      data_template:
        title: >
          Activity high at
          {{ states.sensor.yolo2msghub_event.attributes.yolo2msghub.date | int | timestamp_custom("%a %b %d %I:%M %p") }}
        notification_id: yolo2msghub_activity_high
        message: >
          Current: {{ states.sensor.yolo2msghub_event_activity_count.state }} clients; 
          average {{ states.sensor.yolo2msghub_event_activity_count_mean.state }} clients;
          stdev {{ states.sensor.yolo2msghub_event_activity_count_statistics_mean.attributes.standard_deviation }} clients
    - service: mqtt.publish
      data_template:
        topic: 'status/yolo2msghub_activity/download'
        retain: false
        payload: >
          {{ states.sensor.yolo2msghub_event_activity_count_statistics_mean.attributes }}

- id: yolo2msghub_activity_high_dismiss
  alias: yolo2msghub_activity_high_dismiss
  initial_state: on
  trigger:
    platform: state
    entity_id: binary_sensor.yolo2msghub_activity_high
  condition:
    - condition: template
      value_template: >
        {{ states.binary_sensor.yolo2msghub_activity_high.state == 'off' }}
  action:
    - service: persistent_notification.dismiss
      data_template:
        notification_id: yolo2msghub_activity_high

- id: yolo2msghub_activity_low_persistent
  alias: yolo2msghub_activity_low_persistent
  initial_state: on
  trigger:
    platform: state
    entity_id: binary_sensor.yolo2msghub_activity_low_persistent
  condition:
    - condition: template
      value_template: >
        {{ states.binary_sensor.yolo2msghub_activity_low_persistent.state == 'on' }}
  action:
    - service: persistent_notification.create
      data_template:
        title: >
          Activity lowing at
          {{ states.sensor.yolo2msghub_event.attributes.yolo2msghub.date | int | timestamp_custom("%a %b %d %I:%M %p") }}
        notification_id: yolo2msghub_activity_low
        message: >
          Current: {{ states.sensor.yolo2msghub_event_activity_count.state }} clients; 
          average {{ states.sensor.yolo2msghub_event_activity_count_mean.state }} clients;
          average stdev {{ states.sensor.yolo2msghub_event_activity_count_stdev_mean.state }} clients
    - service: mqtt.publish
      data_template:
        topic: 'status/yolo2msghub_activity/download/stdev'
        retain: false
        payload: >
          {{ states.sensor.yolo2msghub_event_activity_count_stdev_mean.attributes }}

- id: yolo2msghub_activity_high_persistent
  alias: yolo2msghub_activity_high_persistent
  initial_state: on
  trigger:
    platform: state
    entity_id: binary_sensor.yolo2msghub_activity_high_persistent
  condition:
    - condition: template
      value_template: >
        {{ states.binary_sensor.yolo2msghub_activity_high_persistent.state == 'on' }}
  action:
    - service: persistent_notification.create
      data_template:
        title: >
          Activity improving at
          {{ states.sensor.yolo2msghub_event.attributes.yolo2msghub.date | int | timestamp_custom("%a %b %d %I:%M %p") }}
        notification_id: yolo2msghub_activity_high
        message: >
          Current: {{ states.sensor.yolo2msghub_event_activity_count.state }} clients; 
          average {{ states.sensor.yolo2msghub_event_activity_count_mean.state }} clients;
          average stdev {{ states.sensor.yolo2msghub_event_activity_count_stdev_mean.state }} clients
    - service: mqtt.publish
      data_template:
        topic: 'status/yolo2msghub_activity/download/stdev'
        retain: false
        payload: >
          {{ states.sensor.yolo2msghub_event_activity_count_stdev_mean.attributes }}
