homeassistant:
  name: !secret ha-name
  unit_system: imperial
  time_zone: !secret ha-timezone
  customize: !include customize.yaml

http:
  server_port: !secret server-port
  base_url: !secret base-url
  cors_allowed_origins:
    - https://google.com
    - https://www.home-assistant.io
    - http://cdn.clustrmaps.com

## FAVICON
favicon:
  title: !secret ha-name
  icon_path: /local/favicons/

## DEFAULT

mobile_app:
system_health:
hassio:
cloud:
config:
map:
sun:

frontend:
  javascript_version: latest
  themes: !include_dir_merge_named themes
  extra_html_url:
    - http://clustrmaps.com/map_v2.png?cl=ffffff&w=a&t=n&d=xr2Q2vt76X42HBH3uchXdk6LOOAJDVqAySTTK3bDWsM

updater:
  reporting: no
  include_used_components: false

###
### DEVICE_TRACKER
###

device_tracker nmap_tracker:
  - platform: nmap_tracker
    hosts: 192.168.1.0/24
    home_interval: 10
    interval_seconds: 30
    new_device_defaults:
      track_new_devices: true
      hide_if_away: false
    consider_home: 180
    exclude:
      - 192.168.1.1
      - 192.168.1.2
      - 192.168.1.251

device_tracker mqtt_tracker:
  - platform: mqtt
    devices:
      dogpond: 'motion/+/dogpond/status/found'
      dogyard: 'motion/+/dogyard/status/found'
      woodshed: 'motion/+/woodshed/status/found'
      frontwalk: 'motion/+/frontwalk/status/found'
      laundry: 'motion/+/laundry/status/found'

###
### MQTT
###

mqtt:
  broker: !secret mqtt-broker
  port: !secret mqtt-port
  username: !secret mqtt-username
  password: !secret mqtt-password

###
### LOGGER component
###

logger:
  default: error
  logs:
    homeassistant.core: info
    homeassistant.setup: error
    homeassistant.loader: error
    homeassistant.components: error
    homeassistant.components.sensor: error
    homeassistant.components.automation: error
    homeassistant.components.template.binary_sensor: error
    homeassistant.components.template.sensor: error
    homeassistant.components.mqtt.sensor: error
    homeassistant.components.recorder: error
    homeassistant.components.recorder.util: error
    homeassistant.components.statistics.sensor: fatal

###
### RECORDER, HISTORY, LOGBOOK components
###

recorder: !include recorder.yaml
history: !include history.yaml
logbook: !include logbook.yaml

###
### PRIMARY components
###

group: !include groups.yaml
automation: !include automations.yaml
history_graph: !include history_graphs.yaml
counter: !include counters.yaml
input_boolean: !include input_booleans.yaml
input_text: !include input_texts.yaml
input_select: !include input_selects.yaml
input_number: !include input_numbers.yaml

###
### INFLUX
###

#influxdb:
#  host: !secret influxdb-host
#  port: 8086
#  database: homeassistant
#  username: homeassistant
#  password: !secret influxdb-password
#  max_retries: 3
#  default_measurement: state

###
### HOSTIP
###

sensor hostip:
  - platform: command_line
    command: echo '{"date":'$(date "+%s")',"hostname":"'$(hostname)'","ipv4":"'$(ip addr | egrep "global" | sed "s/.* \([0-9\.]*\)\/.*/\1/" | head -1)'"}'
    name: hostip
    scan_interval: 14400
    command_timeout: 30
    json_attributes:
      - date
      - hostname
      - ipv4
    value_template: >
      {%- if value_json is defined -%}
        {{ value_json.date | int | timestamp_custom("%a %b %d @ %I:%M %p") }}
      {%- else -%}null{%- endif -%}

###
### UNAME
###

sensor uname:
  - platform: command_line
    command: echo '{"date":'$(date "+%s")',"hardware":"'$(uname -m)'","nodename":"'$(uname -n)'","processor":"'$(uname -p)'","os_release":"'$(uname -r)'","os_name":"'$(uname -s)'","os_version":"'$(uname -v)'"}'
    name: uname
    scan_interval: 14400
    command_timeout: 30
    json_attributes:
      - date
      - hardware
      - nodename
      - os_release
      - os_name
      - os_version
    value_template: >
      {%- if value_json is defined -%}
        {{ value_json.date | int | timestamp_custom("%a %b %d @ %I:%M %p") }}
      {%- else -%}null{%- endif -%}

###
### PANEL
###
      
panel_iframe:
  netdata:
    title: NetData
    icon: mdi:speedometer
    url: !secret netdata
  hznmonitor:
    title: HZN monitor
    icon: mdi:factory
    url: !secret hznmonitor 
#  edgex:
#    title: EdgeX
#    icon: mdi:mixer
#    url: !secret edgex-url
  digits:
    title: DIGITS
    icon: mdi:fingerprint
    url: !secret digits-url
#  grafana:
#    title: Grafana
#    icon: mdi:graphql
#    url: !secret grafana-url
  couchdb:
    title: CouchDB
    icon: mdi:sofa
    url: !secret couchdb-url
#  consul:
#    title: Consul
#    icon: mdi:passport
#    url: !secret consul-url

## WEBLINKS
weblink:
  entities:
    # this site
    - name: this_site
      url: https://github.com/dcmartin/horizon.dcmartin.com/blob/master/README.md
      icon: mdi:source-repository
    # hassio-addons
    - name: sdr2msghub_addon
      url: https://github.com/dcmartin/hassio-addons/blob/master/sdr2msghub/README.md
      icon: mdi:radio
    - name: kafka2mqtt4yolo_addon
      url: https://github.com/dcmartin/hassio-addons/blob/master/kafka2mqtt4yolo/README.md
      icon: mdi:message-text-outline
    # examples
    - name: sdr2msghub
      url: https://github.com/open-horizon/examples/tree/master/edge/msghub/sdr2msghub
      icon: mdi:radio
    # open-horizon patterns
    - name: yolo2msghub
      url: https://github.com/dcmartin/open-horizon/blob/master/yolo2msghub/README.md
      icon: mdi:glasses
    - name: motion2mqtt
      url: https://github.com/dcmartin/open-horizon/blob/master/motion2mqtt/README.md
      icon: mdi:video
    - name: hznsetup
      url: https://github.com/dcmartin/open-horizon/blob/master/hznsetup/README.md/
      icon: mdi:hospital-building
    - name: startup
      url: https://github.com/dcmartin/open-horizon/blob/master/startup/README.md/
      icon: mdi:baby
    # open-horizon services
    - name: hznmonitor
      url: https://github.com/dcmartin/open-horizon/blob/master/hznmonitor/README.md/
      icon: mdi:factory
    - name: yolo
      url: https://github.com/dcmartin/open-horizon/blob/master/yolo/README.md/
      icon: mdi:eye
    - name: yolo4motion
      url: https://github.com/dcmartin/open-horizon/blob/master/yolo4motion/README.md/
      icon: mdi:comment-eye-outline
    - name: wan
      url: https://github.com/dcmartin/open-horizon/blob/master/wan/README.md/
      icon: mdi:wan
    - name: cpu
      url: https://github.com/dcmartin/open-horizon/blob/master/cpu/README.md/
      icon: mdi:percent
    - name: hal
      url: https://github.com/dcmartin/open-horizon/blob/master/hal/README.md/
      icon: mdi:desktop-classic
    - name: mqtt
      url: https://github.com/dcmartin/open-horizon/blob/master/mqtt/README.md/
      icon: mdi:mmessage-text
    - name: mqtt2kafka
      url: https://github.com/dcmartin/open-horizon/blob/master/mqtt2kafka/README.md/
      icon: mdi:message-text-outline
    - name: master
      url: http://horizon.dcmartin.com:3092
      icon: mdi:link
    - name: beta
      url: http://horizon-vm.local:3092
      icon: mdi:link
    - name: edgex
      url: http://edgex.dcmartin.com:8500/ui
      icon: mdi:link

###
### EXCHANGE
###

sensor exchange: !include sensor.exchange.yaml
binary_sensor exchange: !include binary_sensor.exchange.yaml

###
### STARTUP
###

sensor startup: !include sensor.startup.yaml
binary_sensor startup: !include binary_sensor.startup.yaml

###
### YOLO2MSGHUB
###

sensor yolo2msghub: !include sensor.yolo2msghub.yaml
binary_sensor yolo2msghub: !include binary_sensor.yolo2msghub.yaml
camera yolo2msghub: !include camera.yolo2msghub.yaml

###
### SDR2MSGHUB
###

sensor sdr2msghub: !include sensor.sdr2msghub.yaml
binary_sensor sdr2msghub: !include binary_sensor.sdr2msghub.yaml

###
### HZNMONITOR
###

sensor hznmonitor: !include sensor.hznmonitor.yaml
binary_sensor hznmonitor: !include binary_sensor.hznmonitor.yaml

###
### HZNSETUP
###

sensor hznsetup: !include sensor.hznsetup.yaml
binary_sensor hznsetup: !include binary_sensor.hznsetup.yaml

###
### INTERNET TEST
###

sensor internet: !include sensor.internet.yaml
binary_sensor internet: !include binary_sensor.internet.yaml
            
###
### MOTION
###

sensor motion: !include sensor.motion.yaml
binary_sensor motion: !include binary_sensor.motion.yaml

# sensor motion: !include_dir_merge_named motion.sensors
# binary_sensor motion: !include_dir_merge_named motion.binary_sensors
camera motion: !include_dir_merge_list motion/cameras/

## frontdoor
sensor motion_frontdoor: !include sensor.motion.frontdoor.yaml
binary_sensor motion_frontdoor: !include binary_sensor.motion.frontdoor.yaml

## woodshed
sensor motion_woodshed: !include sensor.motion.woodshed.yaml
binary_sensor motion_woodshed: !include binary_sensor.motion.woodshed.yaml

## frontwalk
sensor motion_frontwalk: !include sensor.motion.frontwalk.yaml
binary_sensor motion_frontwalk: !include binary_sensor.motion.frontwalk.yaml

## laundry
sensor motion_laundry: !include sensor.motion.laundry.yaml
binary_sensor motion_laundry: !include binary_sensor.motion.laundry.yaml

## dogpond
sensor motion_dogpond: !include sensor.motion.dogpond.yaml
binary_sensor motion_dogpond: !include binary_sensor.motion.dogpond.yaml

## dogyard
sensor motion_dogyard: !include sensor.motion.dogyard.yaml
binary_sensor motion_dogyard: !include binary_sensor.motion.dogyard.yaml

## diningroom
sensor motion_diningroom: !include sensor.motion.diningroom.yaml
binary_sensor motion_diningroom: !include binary_sensor.motion.diningroom.yaml
