###
## config-client.yaml
###

homeassistant:
  name: !secret ha-name
  unit_system: imperial
  time_zone: !secret ha-timezone
  latitude: !secret ha-latitude
  longitude: !secret ha-longitude
  customize: !include customize.yaml

http:
  server_port: !secret ha-port
#  base_url: !secret ha-url
#  trusted_networks:
#    - !secret ha-ip
  ip_ban_enabled: false
#  login_attempts_threshold: 0
  cors_allowed_origins:
    - https://google.com
    - https://www.home-assistant.io
    - http://cdn.clustrmaps.com

## DEFAULT
default_config:
mobile_app:
system_health:
hassio:
config:
cloud:
person:
map:
sun:
zone:
zeroconf:
ssdp:

influxdb:
  host: !secret influxdb-host
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret influxdb-password
  max_retries: 3
  default_measurement: state

# tplink
tplink:
  discovery: !secret tplink-discovery

python_script:

frontend:
  javascript_version: latest
  themes: !include_dir_merge_named themes
  extra_html_url:
    - http://clustrmaps.com/map_v2.png?cl=ffffff&w=a&t=n&d=xr2Q2vt76X42HBH3uchXdk6LOOAJDVqAySTTK3bDWsM

updater:
  reporting: no
  include_used_components: false

###
### MQTT
###

mqtt:
  broker: !secret mqtt-broker
  port: !secret mqtt-port
  username: !secret mqtt-username
  password: !secret mqtt-password

sensor datetime:
  - platform: time_date
    display_options:
      - date
      - time

###
## RECORDER, HISTORY, LOGBOOK components
###

logger: !include logger.yaml
recorder: !include recorder.yaml
history: !include history.yaml
logbook: !include logbook.yaml
#weblink: !include weblinks.yaml

###
## directory configuration
###

sensor: !include_dir_merge_list sensor/
binary_sensor: !include_dir_merge_list binary_sensor/
group: !include_dir_merge_named group/
automation: !include_dir_merge_list automation/
counter: !include_dir_merge_named counter/
#history_graph: !include_dir_merge_named history_graph/
camera: !include_dir_merge_list camera/
device_tracker: !include_dir_merge_list device_tracker/
shell_command: !include_dir_merge_named shell_command/

input_select: !include_dir_merge_named input_select/
input_boolean: !include_dir_merge_named input_boolean/
input_text: !include_dir_merge_named input_text/
input_number: !include_dir_merge_named input_number/

###
## PANEL
###
      
panel_iframe: !include_dir_merge_named panel_iframe/
