###
## config-client.yaml
###

homeassistant:
  customize: !include customize.yaml
  media_dirs:
    history: '/media/Motion-√ÉüëÅ'
    cache: '/config/www/images/motion'

http:
  server_port: !secret ha-port
  ip_ban_enabled: false
  cors_allowed_origins:
    - https://google.com
    - https://www.home-assistant.io

## DEFAULT
default_config:
mobile_app:
system_health:
hassio:
config:
cloud:
person:
map:
sun:
zone:
zeroconf:
ssdp:
python_script:

# text-to-speech
tts:
  - platform: google_translate

favicon:
  title: 'Motion √ÉüëÅ'
  icon_path: /local/favicons/

# influxdb
influxdb: !include influxdb.yaml

# twilio
twilio:
  account_sid: !secret twilio-account-sid
  auth_token: !secret twilio-auth-token

# tplink
tplink:
  discovery: !secret tplink-discovery

frontend:
  themes: !include_dir_merge_named themes

updater:
  reporting: no
  include_used_components: false

###
### MQTT
###

mqtt:
  broker: !secret mqtt-broker
  port: !secret mqtt-port
  username: !secret mqtt-username
  password: !secret mqtt-password

sensor datetime:
  - platform: time_date
    display_options:
      - date
      - time

###
## RECORDER, HISTORY, LOGBOOK components
###

logger: !include logger.yaml
recorder: !include recorder.yaml
history: !include history.yaml
logbook: !include logbook.yaml

###
## directory configuration
###

sensor: !include_dir_merge_list sensor/
binary_sensor: !include_dir_merge_list binary_sensor/
automation: !include_dir_merge_list automation/
group: !include_dir_merge_named group/
counter: !include_dir_merge_named counter/
camera: !include_dir_merge_list camera/
device_tracker: !include_dir_merge_list device_tracker/
shell_command: !include_dir_merge_named shell_command/
notify: !include_dir_merge_list notify/

input_select: !include_dir_merge_named input_select/
input_boolean: !include_dir_merge_named input_boolean/
input_text: !include_dir_merge_named input_text/
input_number: !include_dir_merge_named input_number/

###
## PANEL
###
      
panel_iframe: !include_dir_merge_named panel_iframe/

# input_datetime
input_datetime: !include_dir_merge_named input_datetime/

# tensorflow
image_processing: !include_dir_merge_list image_processing/

# iOS smartphone
ios:
  push:
    categories:
      - identifier: 'motion_smartphone_alert'
        name: 'Alert smartphone'
        actions:
          - identifier: 'motion_smartphone_alert_notify'
            title: 'Notify'
            activationMode: 'background'
            authenticationRequired: false
            destructive: true
            behavior: 'default'
          - identifier: 'motion_smartphone_alert_dismiss'
            title: 'Dismiss'
            activationMode: 'background'
            authenticationRequired: false
            destructive: false
            behavior: 'default'
      - identifier: 'motion_smartphone_ask'
        name: 'Ask smartphone'
        actions:
          - identifier: 'motion_smartphone_ask_update'
            title: 'Update'
            activationMode: 'background'
            authenticationRequired: false
            destructive: false
            behavior: 'textInput'
            textInputButtonTitle: 'OK'
            textInputPlaceholder: 'Update'
          - identifier: 'motion_smartphone_ask_confirm'
            title: 'Confirm'
            activationMode: 'background'
            authenticationRequired: false
            destructive: false
            behavior: 'default'
          - identifier: 'motion_smartphone_ask_deny'
            title: 'Deny'
            activationMode: 'background'
            authenticationRequired: false
            destructive: true 
            behavior: 'default'
