###
## config-client.yaml
###

homeassistant:
  customize: !include customize.yaml
  #name: !secret ha-name
  #unit_system: imperial
  #time_zone: !secret ha-timezone
  #latitude: !secret ha-latitude
  #longitude: !secret ha-longitude

http:
  server_port: !secret ha-port
  ip_ban_enabled: false
  cors_allowed_origins:
    - https://google.com
    - https://www.home-assistant.io
#  base_url: !secret ha-url
#  trusted_networks:
#    - !secret ha-ip
#  login_attempts_threshold: 0

## DEFAULT
default_config:
mobile_app:
system_health:
hassio:
config:
cloud:
ios:
person:
map:
sun:
zone:
zeroconf:
ssdp:

# text-to-speech
tts:
  - platform: google_translate

favicon:
  title: 'Motion √ÉüëÅ'
  icon_path: /local/favicons/

influxdb:
  host: !secret influxdb-host
  port: 8086
  database: !secret influxdb-database
  username: !secret influxdb-username
  password: !secret influxdb-password
  max_retries: 3
  default_measurement: state

# tplink
tplink:
  discovery: !secret tplink-discovery

python_script:

frontend:
  themes: !include_dir_merge_named themes

updater:
  reporting: no
  include_used_components: false

###
### MQTT
###

mqtt:
  broker: !secret mqtt-broker
  port: !secret mqtt-port
  username: !secret mqtt-username
  password: !secret mqtt-password

sensor datetime:
  - platform: time_date
    display_options:
      - date
      - time

###
## RECORDER, HISTORY, LOGBOOK components
###

logger: !include logger.yaml
recorder: !include recorder.yaml
history: !include history.yaml
logbook: !include logbook.yaml

###
## directory configuration
###

sensor: !include_dir_merge_list sensor/
binary_sensor: !include_dir_merge_list binary_sensor/
automation: !include_dir_merge_list automation/
group: !include_dir_merge_named group/
counter: !include_dir_merge_named counter/
camera: !include_dir_merge_list camera/
device_tracker: !include_dir_merge_list device_tracker/
shell_command: !include_dir_merge_named shell_command/
notify: !include_dir_merge_list notify/

input_select: !include_dir_merge_named input_select/
input_boolean: !include_dir_merge_named input_boolean/
input_text: !include_dir_merge_named input_text/
input_number: !include_dir_merge_named input_number/

###
## PANEL
###
      
panel_iframe: !include_dir_merge_named panel_iframe/
