###
## sensor/motion/config.yaml
###

- platform: template
  sensors:
    motion_group:
      value_template: >-
        {% if states.input_text.motion_group is defined %}
          {{ states.input_text.motion_group.state }}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_device:
      value_template: >-
        {% if states.input_text.motion_device is defined %}
          {{ states.input_text.motion_device.state }}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_client:
      value_template: >-
        {% if states.input_text.motion_client is defined %}
          {{ states.input_text.motion_client.state }}
        {% else %}null{% endif %}


- platform: template
  sensors:
    motion_domain_sensor_count:
      friendly_name: '# sensor'
      icon_template: 'mdi:counter'
      value_template: >-
        {{ states.sensor|length }}

- platform: template
  sensors:
    motion_domain_camera_count:
      friendly_name: '# camera'
      icon_template: 'mdi:counter'
      value_template: >-
        {{ states.camera|length }}

- platform: template
  sensors:
    motion_domain_counter_count:
      friendly_name: '# counter'
      icon_template: 'mdi:counter'
      value_template: >-
        {{ states.counter|length }}

- platform: template
  sensors:
    motion_domain_automations_count:
      friendly_name: '# automation'
      icon_template: 'mdi:counter'
      value_template: >-
        {{ states.automation|length }}

- platform: template
  sensors:
    motion_domain_binary_sensor_count:
      friendly_name: '# binary_sensor'
      icon_template: 'mdi:counter'
      value_template: >-
        {{ states.binary_sensor|length }}

- platform: template
  sensors:
    motion_domain_input_boolean_count:
      friendly_name: '# input_boolean'
      icon_template: 'mdi:counter'
      value_template: >-
        {{ states.input_boolean|length }}

- platform: template
  sensors:
    motion_domain_input_number_count:
      friendly_name: '# input_number'
      icon_template: 'mdi:counter'
      value_template: >-
        {{ states.input_number|length }}

- platform: template
  sensors:
    motion_domain_input_text_count:
      friendly_name: '# input_text'
      icon_template: 'mdi:counter'
      value_template: >-
        {{ states.input_text|length }}

- platform: template
  sensors:
    motion_domain_input_select_count:
      friendly_name: '# input_select'
      icon_template: 'mdi:counter'
      value_template: >-
        {{ states.input_select|length }}
