###
## sensor/motion/config.yaml
###

- platform: template
  sensors:
    motion_group:
      friendly_name: Group
      icon_template: 'mdi:camera-control'
      value_template: >-
        {% if states.input_text.motion_group is defined %}
          {{ states.input_text.motion_group.state }}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_device:
      friendly_name: Device
      icon_template: 'mdi:raspberry-pi'
      value_template: >-
        {% if states.input_text.motion_device is defined %}
          {{ states.input_text.motion_device.state }}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_client:
      friendly_name: Client
      icon_template: 'mdi:webcam'
      value_template: >-
        {% if states.input_text.motion_client is defined %}
          {{ states.input_text.motion_client.state }}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_domain_sensor_count:
      friendly_name: 'Σ sensor'
      icon_template: 'mdi:counter'
      value_template: >-
        {{ states.sensor|length }}

- platform: template
  sensors:
    motion_domain_camera_count:
      friendly_name: 'Σ camera'
      icon_template: 'mdi:counter'
      value_template: >-
        {{ states.camera|length }}

- platform: template
  sensors:
    motion_domain_counter_count:
      friendly_name: 'Σ counter'
      icon_template: 'mdi:counter'
      value_template: >-
        {{ states.counter|length }}

- platform: template
  sensors:
    motion_domain_group_count:
      friendly_name: 'Σ group'
      icon_template: 'mdi:counter'
      value_template: >-
        {{ states.group|length }}

- platform: template
  sensors:
    motion_domain_automation_count:
      friendly_name: 'Σ automation'
      icon_template: 'mdi:counter'
      value_template: >-
        {{ states.automation|length }}

- platform: template
  sensors:
    motion_domain_binary_sensor_count:
      friendly_name: 'Σ binary_sensor'
      icon_template: 'mdi:counter'
      value_template: >-
        {{ states.binary_sensor|length }}

- platform: template
  sensors:
    motion_domain_input_boolean_count:
      friendly_name: 'Σ input_boolean'
      icon_template: 'mdi:counter'
      value_template: >-
        {{ states.input_boolean|length }}

- platform: template
  sensors:
    motion_domain_input_number_count:
      friendly_name: 'Σ input_number'
      icon_template: 'mdi:counter'
      value_template: >-
        {{ states.input_number|length }}

- platform: template
  sensors:
    motion_domain_input_text_count:
      friendly_name: 'Σ input_text'
      icon_template: 'mdi:counter'
      value_template: >-
        {{ states.input_text|length }}

- platform: template
  sensors:
    motion_domain_input_select_count:
      friendly_name: 'Σ input_select'
      icon_template: 'mdi:counter'
      value_template: >-
        {{ states.input_select|length }}

- platform: template
  sensors:
    motion_domain_media_player_count:
      friendly_name: 'Σ media_player'
      icon_template: 'mdi:counter'
      value_template: >-
        {{ states.media_player|length }}
