###
### group/motion/config.yaml
###

motion_config:
  name: motion_config
  icon: mdi:settings
  control: hidden
  entities:
    - input_select.motion_detect_entity
    - sensor.motion_detected_entity_percent
    - input_number.motion_face_detected_percent
    - sensor.motion_face_detected_percent
    - sensor.motion_mqtt_broker
    - sensor.motion_mqtt_port
