
motion_settings:
  name: motion_settings
  control: hidden
  entities:
    - input_select.motion_detect_entity
    - sensor.motion_detect_entity
    - sensor.motion_device_start_camera_count
    - sensor.motion_device_start_camera_names
    - input_boolean.motion_detected_entity_notify
    - input_boolean.motion_detected_notify
    - input_boolean.motion_reset_found
    - input_boolean.motion_reset_lost
    - input_boolean.motion_snapshot
    - input_boolean.motion_snapshot_save
    - input_boolean.motion_status_camera_notify
    - input_number.motion_complete
    - input_number.motion_annotated_ago
    - input_number.motion_detected_ago
    - input_number.motion_detected_entity_ago
    - input_number.motion_annotated_counter_deviation
    - input_number.motion_detected_counter_deviation
    - input_number.motion_detected_entity_counter_deviation
    - input_number.motion_end_counter_deviation
    - input_number.motion_annotated_count_deviation
    - input_number.motion_detected_count_deviation
    - input_number.motion_detected_entity_count_deviation
    - input_number.motion_face_ago
    - input_number.motion_face_detected_ago
    - input_number.motion_face_detected_percent
