###
# group/settings.yaml
###

settings_view:
  name: SETTINGS
  #view: true
  icon: mdi:settings
  entities:
    - group.settings_frontend
    - group.settings_internet
    - group.settings_sdr2msghub
    - group.settings_yolo2msghub
    - group.settings_startup
    - group.motion_settings

settings_frontend:
  name: settings_frontend
  icon: mdi:spray
  entities:
    - input_select.theme_select
    - input_select.homeassistant_url
    - sensor.motion_base_url

settings_internet:
  name: settings_internet
  entities:
    - input_number.internet_deviation
